# vim: set ft=ansible et ts=2 sw=2:
#
# downloads and configures liquidprompt for a user specified in the playbook calling this role
#
---

- name: Clone liquidprompt repo to ~/lp
  git: "repo=https://github.com/nojhan/liquidprompt.git dest=~/lp"
  become_user: "{{ user_to_liquidify }}"

- name: copy defaults file
  copy: 
    remote_src: true
    src: "~/lp/liquidpromptrc-dist" 
    dest: "~/.liquidpromptrc"
    force: no
  become_user: "{{ user_to_liquidify }}"

- name: configure defaults file
  lineinfile:
    path: "~/.liquidpromptrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^LP_HOSTNAME_ALWAYS', line: 'LP_HOSTNAME_ALWAYS=1' }
    - { regexp: '^LP_ENABLE_TIME', line: 'LP_ENABLE_TIME=1' }
    #- { regexp: '^', line: '' } 
  become_user: "{{ user_to_liquidify }}"

- name: add a line to bash to source liquidprompt to start it
  lineinfile:
    path: "~/.bashrc"
    line: "[[ $- = *i* ]] && source ~/lp/liquidprompt"
    create: true
  become_user: "{{ user_to_liquidify }}"

- name: insert/update check to make .bash_profile call .bash_rc if running bash interactively
  blockinfile:
    path: "~/.bash_profile"
    create: true
    block: |
      if [ -f ~/.bashrc ]; then
              . ~/.bashrc
      fi
  become_user: "{{ user_to_liquidify }}"



